# Generated by Django 4.2.8 on 2024-04-05 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_rename_primary_background_color_space_primary_bg_color_and_more'),
        ('boards', '0011_postcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labels',
            new_name='Label',
        ),
    ]
