# Generated by Django 4.2.8 on 2024-04-05 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_rename_labels_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='label',
            new_name='name',
        ),
    ]
